spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recovery?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
    driver-class-name : com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

mybatis-plus:
  type-aliases-package: com.example.recovery.system.*.entity
  type-aliases-super-type: java.lang.Object

prop:
  upload-folder: D:\IDEAwork\recovery\upload\\
server:
  port: 8087

mybatis:
  configuration:
    map-underscore-to-camel-case: true